import os

SQS_ENDPOINT_URL = os.environ.get("SQS_ENDPOINT_URL")

SCAN_QUEUE_URL = os.environ.get(
    "SCAN_QUEUE_URL",
    "http://localhost:9324/000000000000/scan-jobs.fifo",
)

POLL_WAIT_SECONDS = 20

VISIBILITY_TIMEOUT_SECONDS = 300

HEARTBEAT_INTERVAL_SECONDS = 60

HEARTBEAT_EXTENSION_SECONDS = 300

MAX_MESSAGES_PER_POLL = 1

DEDUP_WINDOW_SECONDS = 60
