TRIVY_IMAGE = "aquasec/trivy:latest"

TRIVY_CACHE_VOLUME = "trivy-cache"

TRIVY_SCANNERS = "vuln,secret"

TRIVY_TIMEOUT_SECONDS = 600

MAX_VULNERABILITIES_TO_MODEL = 150

DESCRIPTION_TRUNCATE_CHARS = 200

CVE_MODEL = "gpt-4o"

CVE_TEMPERATURE = 0.0

CVE_TIMEOUT_SECONDS = 90
